spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: spc-provider-dev # 服务名

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: spc-provider-8001

---
server:
  port: 8003
spring:
  profiles: test
  application:
    name: spc-provider-test # 服务名

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: spc-provider-8003